services:
  - type: web
    name: anomaly-api
    env: docker
    dockerfilePath: ./deployment/Dockerfile.api
    region: singapore
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 8000