FROM python:3.10-slim

WORKDIR /app

COPY deployment/api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY deployment/api/ .
COPY deployment/models/ ./models/

EXPOSE 8000

CMD uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}